name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Trigger on new version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create release artifact
        run: |
          mkdir -p build
          cp -r vendor public logs composer.json .gitignore .env.example build/
          cd build && zip -r ../testing-flw-php.zip . && cd ..

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flw-test
          path: testing-flw-php.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: flw-test
          path: .

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: testing-flw-php.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
